name: CICDTEST

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
      with:
        ref: main
    - name: printing where i am and what files here is.
      run: |
        pwd
        ls
    - name: build
      run: |
        make
        ./exe
